# Default TAKT Piece
# Plan -> Architect -> Implement -> AI Review -> Reviewers (parallel: Architect + QA) -> Supervisor Approval
#
# Template Variables (auto-injected by buildInstruction):
#   {iteration}      - Piece-wide turn count (total movements executed across all agents)
#   {max_iterations} - Maximum iterations allowed for the piece
#   {movement_iteration} - Per-movement iteration count (how many times THIS movement has been executed)
#   {task}           - Original user request
#   {previous_response} - Output from the previous movement
#   {user_inputs}    - Accumulated user inputs during piece
#   {report_dir}     - Report directory name (e.g., "20250126-143052-task-summary")

name: default
description: Standard development piece with planning and specialized reviews

max_iterations: 30

stances:
  coding: ../stances/coding.md
  review: ../stances/review.md
  testing: ../stances/testing.md

knowledge:
  architecture: ../knowledge/architecture.md

personas:
  planner: ../personas/planner.md
  architect-planner: ../personas/architect-planner.md
  coder: ../personas/coder.md
  ai-antipattern-reviewer: ../personas/ai-antipattern-reviewer.md
  architecture-reviewer: ../personas/architecture-reviewer.md
  qa-reviewer: ../personas/qa-reviewer.md
  supervisor: ../personas/supervisor.md

instructions:
  plan: ../instructions/plan.md
  architect: ../instructions/architect.md
  implement: ../instructions/implement.md
  ai-review: ../instructions/ai-review.md
  ai-fix: ../instructions/ai-fix.md
  arbitrate: ../instructions/arbitrate.md
  review-arch: ../instructions/review-arch.md
  review-qa: ../instructions/review-qa.md
  fix: ../instructions/fix.md
  supervise: ../instructions/supervise.md

report_formats:
  plan: ../report-formats/plan.md
  architecture-design: ../report-formats/architecture-design.md
  ai-review: ../report-formats/ai-review.md
  architecture-review: ../report-formats/architecture-review.md
  qa-review: ../report-formats/qa-review.md
  validation: ../report-formats/validation.md
  summary: ../report-formats/summary.md

initial_movement: plan

loop_monitors:
  - cycle: [ai_review, ai_fix]
    threshold: 3
    judge:
      persona: supervisor
      instruction_template: |
        The ai_review ↔ ai_fix loop has repeated {cycle_count} times.

        Review the reports from each cycle and determine whether this loop
        is healthy (making progress) or unproductive (repeating the same issues).

        **Reports to reference:**
        - AI Review results: {report:04-ai-review.md}

        **Judgment criteria:**
        - Are new issues being found/fixed in each cycle?
        - Are the same findings being repeated?
        - Are fixes actually being applied?
      rules:
        - condition: Healthy (making progress)
          next: ai_review
        - condition: Unproductive (no improvement)
          next: reviewers

movements:
  - name: plan
    edit: false
    persona: planner
    report:
      name: 00-plan.md
      format: plan
    allowed_tools:
      - Read
      - Glob
      - Grep
      - Bash
      - WebSearch
      - WebFetch
    rules:
      - condition: Requirements are clear and implementable
        next: architect
      - condition: User is asking a question (not an implementation task)
        next: COMPLETE
      - condition: Requirements unclear, insufficient info
        next: ABORT
        appendix: |
          Clarifications needed:
          - {Question 1}
          - {Question 2}
    instruction: plan

  - name: architect
    edit: false
    persona: architect-planner
    report:
      name: 01-architecture.md
      format: architecture-design
    allowed_tools:
      - Read
      - Glob
      - Grep
      - WebSearch
      - WebFetch
    rules:
      - condition: Small task (no design needed)
        next: implement
      - condition: Design complete
        next: implement
      - condition: Insufficient info, cannot proceed
        next: ABORT
    instruction: architect

  - name: implement
    edit: true
    persona: coder
    stance:
      - coding
      - testing
    session: refresh
    report:
      - Scope: 02-coder-scope.md
      - Decisions: 03-coder-decisions.md
    allowed_tools:
      - Read
      - Glob
      - Grep
      - Edit
      - Write
      - Bash
      - WebSearch
      - WebFetch
    permission_mode: edit
    rules:
      - condition: Implementation complete
        next: ai_review
      - condition: No implementation (report only)
        next: ai_review
      - condition: Cannot proceed, insufficient info
        next: ai_review
      - condition: User input required
        next: implement
        requires_user_input: true
        interactive_only: true
    instruction: implement

  - name: ai_review
    edit: false
    persona: ai-antipattern-reviewer
    stance: review
    report:
      name: 04-ai-review.md
      format: ai-review
    allowed_tools:
      - Read
      - Glob
      - Grep
      - WebSearch
      - WebFetch
    rules:
      - condition: No AI-specific issues
        next: reviewers
      - condition: AI-specific issues found
        next: ai_fix
    instruction: ai-review

  - name: ai_fix
    edit: true
    persona: coder
    stance:
      - coding
      - testing
    session: refresh
    allowed_tools:
      - Read
      - Glob
      - Grep
      - Edit
      - Write
      - Bash
      - WebSearch
      - WebFetch
    permission_mode: edit
    rules:
      - condition: AI issues fixed
        next: ai_review
      - condition: No fix needed (verified target files/spec)
        next: ai_no_fix
      - condition: Cannot proceed, insufficient info
        next: ai_no_fix
    instruction: ai-fix

  - name: ai_no_fix
    edit: false
    persona: architecture-reviewer
    stance: review
    allowed_tools:
      - Read
      - Glob
      - Grep
    rules:
      - condition: ai_review's findings are valid (fix required)
        next: ai_fix
      - condition: ai_fix's judgment is valid (no fix needed)
        next: reviewers
    instruction: arbitrate

  - name: reviewers
    parallel:
      - name: arch-review
        edit: false
        persona: architecture-reviewer
        stance: review
        knowledge: architecture
        report:
          name: 05-architect-review.md
          format: architecture-review
        allowed_tools:
          - Read
          - Glob
          - Grep
          - WebSearch
          - WebFetch
        rules:
          - condition: approved
          - condition: needs_fix
        instruction: review-arch

      - name: qa-review
        edit: false
        persona: qa-reviewer
        stance: review
        report:
          name: 06-qa-review.md
          format: qa-review
        allowed_tools:
          - Read
          - Glob
          - Grep
          - WebSearch
          - WebFetch
        rules:
          - condition: approved
          - condition: needs_fix
        instruction: review-qa
    rules:
      - condition: all("approved")
        next: supervise
      - condition: any("needs_fix")
        next: fix

  - name: fix
    edit: true
    persona: coder
    stance:
      - coding
      - testing
    allowed_tools:
      - Read
      - Glob
      - Grep
      - Edit
      - Write
      - Bash
      - WebSearch
      - WebFetch
    permission_mode: edit
    rules:
      - condition: Fix complete
        next: reviewers
      - condition: Cannot proceed, insufficient info
        next: plan
    instruction: fix

  - name: supervise
    edit: false
    persona: supervisor
    stance: review
    report:
      - Validation: 07-supervisor-validation.md
      - Summary: summary.md
    allowed_tools:
      - Read
      - Glob
      - Grep
      - Bash
      - WebSearch
      - WebFetch
    rules:
      - condition: All checks passed
        next: COMPLETE
      - condition: Requirements unmet, tests failing, build errors
        next: plan
    instruction: supervise
